// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	"github.com/aws/aws-sdk-go-v2/service/kinesis"
	"github.com/phogolabs/theta"
)

type FakeKinesisClient struct {
	PutRecordStub        func(context.Context, *kinesis.PutRecordInput, ...func(*kinesis.Options)) (*kinesis.PutRecordOutput, error)
	putRecordMutex       sync.RWMutex
	putRecordArgsForCall []struct {
		arg1 context.Context
		arg2 *kinesis.PutRecordInput
		arg3 []func(*kinesis.Options)
	}
	putRecordReturns struct {
		result1 *kinesis.PutRecordOutput
		result2 error
	}
	putRecordReturnsOnCall map[int]struct {
		result1 *kinesis.PutRecordOutput
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeKinesisClient) PutRecord(arg1 context.Context, arg2 *kinesis.PutRecordInput, arg3 ...func(*kinesis.Options)) (*kinesis.PutRecordOutput, error) {
	fake.putRecordMutex.Lock()
	ret, specificReturn := fake.putRecordReturnsOnCall[len(fake.putRecordArgsForCall)]
	fake.putRecordArgsForCall = append(fake.putRecordArgsForCall, struct {
		arg1 context.Context
		arg2 *kinesis.PutRecordInput
		arg3 []func(*kinesis.Options)
	}{arg1, arg2, arg3})
	stub := fake.PutRecordStub
	fakeReturns := fake.putRecordReturns
	fake.recordInvocation("PutRecord", []interface{}{arg1, arg2, arg3})
	fake.putRecordMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeKinesisClient) PutRecordCallCount() int {
	fake.putRecordMutex.RLock()
	defer fake.putRecordMutex.RUnlock()
	return len(fake.putRecordArgsForCall)
}

func (fake *FakeKinesisClient) PutRecordCalls(stub func(context.Context, *kinesis.PutRecordInput, ...func(*kinesis.Options)) (*kinesis.PutRecordOutput, error)) {
	fake.putRecordMutex.Lock()
	defer fake.putRecordMutex.Unlock()
	fake.PutRecordStub = stub
}

func (fake *FakeKinesisClient) PutRecordArgsForCall(i int) (context.Context, *kinesis.PutRecordInput, []func(*kinesis.Options)) {
	fake.putRecordMutex.RLock()
	defer fake.putRecordMutex.RUnlock()
	argsForCall := fake.putRecordArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeKinesisClient) PutRecordReturns(result1 *kinesis.PutRecordOutput, result2 error) {
	fake.putRecordMutex.Lock()
	defer fake.putRecordMutex.Unlock()
	fake.PutRecordStub = nil
	fake.putRecordReturns = struct {
		result1 *kinesis.PutRecordOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeKinesisClient) PutRecordReturnsOnCall(i int, result1 *kinesis.PutRecordOutput, result2 error) {
	fake.putRecordMutex.Lock()
	defer fake.putRecordMutex.Unlock()
	fake.PutRecordStub = nil
	if fake.putRecordReturnsOnCall == nil {
		fake.putRecordReturnsOnCall = make(map[int]struct {
			result1 *kinesis.PutRecordOutput
			result2 error
		})
	}
	fake.putRecordReturnsOnCall[i] = struct {
		result1 *kinesis.PutRecordOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeKinesisClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeKinesisClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ theta.KinesisClient = new(FakeKinesisClient)
